---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Chart.Name | quote }}
spec:
  selector:
    app: {{ .Chart.Name | quote }}
  type: ClusterIP
  ports:
    - name: http
      port: {{ pluck .Values.global.env .Values.app.port | first | default .Values.app.port._default }}
    - name: http-metrics
      port: {{ pluck .Values.global.env .Values.app.metrics_port | first | default .Values.app.metrics_port._default }}