{{- if ( pluck .Values.global.env .Values.app.autoscaler.hpa.enabled | first | default .Values.app.autoscaler.hpa.enabled._default ) }}
{{- if gt ( pluck .Values.global.env .Values.app.replicas.count | first | default .Values.app.replicas.count._default | int) 0 }}
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Chart.Name | quote }}
spec:
  maxReplicas: {{ pluck .Values.global.env .Values.app.replicas.max_count | first | default .Values.app.replicas.max_count._default }}
  minReplicas: {{ pluck .Values.global.env .Values.app.replicas.count | first | default .Values.app.replicas.count._default }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Chart.Name | quote }}
  metrics:
  - type: Pods
    pods:
      metricName: cpu_5m
      targetAverageValue: {{ pluck .Values.global.env .Values.app.autoscaler.hpa.hpa_target_cpu | first | default .Values.app.autoscaler.hpa.hpa_target_cpu._default }}
{{- end }}
{{- end }}