{{- if ( pluck .Values.global.env .Values.app.autoscaler.vpa.enabled | first | default .Values.app.autoscaler.vpa.enabled._default ) }}
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ .Chart.Name | quote }}
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: {{ .Chart.Name | quote }}
  updatePolicy:
    updateMode: "Off"
{{- end }}