{{- if ( pluck .Values.global.env .Values.app.ingress.ssl.enabled | first | default .Values.app.ingress.ssl.enabled._default ) }}
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ printf "%s-tls" .Chart.Name }}
spec:
  secretName: {{ printf "%s-tls" .Chart.Name }}
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  commonName: {{ pluck .Values.global.env .Values.app.ingress.domain | first | default .Values.app.ingress.domain._default | quote }}
  dnsNames:
  - {{ pluck .Values.global.env .Values.app.ingress.domain | first | default .Values.app.ingress.domain._default | quote }}
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - {{ pluck .Values.global.env .Values.app.ingress.domain | first | default .Values.app.ingress.domain._default | quote }}
{{- end }}